#!/usr/bin/env php

<?php

/**
 * Lenevor Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file license.md.
 * It is also available through the world-wide-web at this URL:
 * https://lenevor.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Lenevor.com so we can send you a copy immediately.
 *
 * @package     Lenevor
 * @subpackage  Base
 * @link        https://lenevor.com
 * @copyright   Copyright (c) 2019 - 2025 Alexander Campo <jalexcam@gmail.com>
 * @license     https://opensource.org/licenses/BSD-3-Clause New BSD license or see https://lenevor.com/license or see /license.md
 */

use Syscodes\Components\Console\Input\ArgvInput;

/**
 * Refuse to run prime when called from php-cgi !
 */
if (substr(php_sapi_name(), 0, 3) === 'cgi')
{
    die("The use of prime is not supported when running php-cgi. Prime needs php-cli to function!\n\n");
}

// Register the Composer autoloader...
if (file_exists(__DIR__.'/../vendor/autoload.php'))
    require __DIR__.'/../vendor/autoload.php';

// Calls all the pathname of settings for manages an application web...
$paths = require __DIR__.'/config/paths.php';

// Register bootstrap from web resource bundle...
if (file_exists($paths['path.sys'].'/src/bundles/WebResourceBundle/Bootstrap/bootstrap.php'))
    require $paths['path.sys'].'/src/bundles/WebResourceBundle/Bootstrap/bootstrap.php';

// Bootstrap the application Lenevor and handle the command...                                              
$status = (require_once $paths['path.bootstrap'].'/app.php')
    ->handleCommand(new ArgvInput());

exit($status);