<?php 

/*
|------------------------------------------------------------------------
| Lenevor Config File Map                                                      
|------------------------------------------------------------------------
|
| This file is automatically generated for build filemap. 
|
| Note: [!!] Do not modify it directly.
|
*/
return [
   
];