<?php

/*
|------------------------------------------------------------------------
| Lenevor Config Class PSR-4                                                      
|------------------------------------------------------------------------
|
| This file is automatically generated for build psr-4. 
|
| Note: [!!] Do not modify it directly.
|
*/
return [
    
];