<?php 

/*
|------------------------------------------------------------------------
| Lenevor Config Class Map                                                      
|------------------------------------------------------------------------
|
| This file is automatically generated for build classmap. 
|
| Note: [!!] Do not modify it directly.
|
*/
return [];